# vim:fileencoding=utf-8:foldmethod=marker

include ./colorscheme/current-theme.conf

map kitty_mod+s>g goto_session ~/.local/share/kitty/sessions
map kitty_mod+s>w save_as_session --use-foreground-process --base-dir ~/.local/share/kitty/sessions
map kitty_mod+s>s save_as_session --use-foreground-process --base-dir ~/.local/share/kitty/sessions --match=session:. .
map kitty_mod+s>q close_session

map ctrl+j kitten pass_keys.py bottom ctrl+j
map ctrl+k kitten pass_keys.py top    ctrl+k
map ctrl+h kitten pass_keys.py left   ctrl+h
map ctrl+l kitten pass_keys.py right  ctrl+l

map ctrl+alt+h resize_window narrower
map ctrl+alt+l resize_window wider
map ctrl+alt+k resize_window taller
map ctrl+alt+j resize_window shorter
map ctrl+alt+0 resize_window reset

map kitty_mod+a>t launch --type=background kitten quick-access-terminal --config ~/.config/kitty/quick_access_terminal.conf --instance-group todo "$HOME/.config/kitty/scripts/show-todo.sh"
map kitty_mod+a>n launch --type=background kitten quick-access-terminal --config ~/.config/kitty/quick_access_terminal.conf --instance-group note "$HOME/.config/kitty/scripts/show-notes.sh"

font_family monospace

font_size 9

undercurl_style thin-sparse

cursor_shape block

cursor_trail 0

cursor_trail_start_threshold 3

scrollback_lines 10000

scrollbar never

scrollback_pager nvim -u ~/.config/nvim/init.lua --cmd 'set eventignore=FileType' +'setlocal buftype=nofile bufhidden=hide noswapfile' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'silent! %s/\v($\n)+%$//e' +'$' -

touch_scroll_multiplier 5.0

show_hyperlink_targets yes

underline_hyperlinks always

paste_actions quote-urls-at-prompt,confirm,confirm-if-large

strip_trailing_spaces smart

repaint_delay 32

enable_audio_bell yes

visual_bell_duration 0.3 linear

enabled_layouts fat,stack,tall,grid

window_resize_step_cells 1
window_resize_step_lines 1

window_padding_width 10

hide_window_decorations yes

confirm_os_window_close 1

tab_bar_filter session:~

tab_bar_align center

tab_bar_min_tabs 1

tab_bar_style custom

tab_fade 0 0 0 0

tab_bar_style custom

tab_title_template "{custom}"

remote_control_password "lazygit-token" launch

allow_remote_control yes

listen_on unix:@kitty

watcher focus_watcher.py

shell_integration enabled

notify_on_cmd_finish unfocused 5.0 command notify-send "job finished with status: %s" %c

map kitty_mod+c copy_to_clipboard

map kitty_mod+v paste_from_clipboard

map kitty_mod+p scroll_to_prompt -1

map kitty_mod+n scroll_to_prompt 1

map kitty_mod+h show_scrollback

map kitty_mod+enter new_window_with_cwd

map kitty_mod+n new_os_window_with_cwd

map kitty_mod+t new_tab_with_cwd

map kitty_mod+l>n next_layout
map kitty_mod+l>f goto_layout fat
map kitty_mod+l>t goto_layout tall
map kitty_mod+l>s goto_layout stack
map kitty_mod+l>g goto_layout grid

map kitty_mod+delete clear_terminal scroll active

map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
