# env stuff
source= ./confs/env.conf

# startup stuff
source= ./confs/startup.conf

# monitor stuff
source= ./confs/monitor.conf

# animations stuff
source= ./confs/animations.conf

# effects and animations stuff
source= ./confs/bind.conf

# input stuff
source= ./confs/input.conf

# appearance stuff
source= ./confs/appearance.conf

# misc stuff
source= ./confs/misc.conf

# scroller stuff
source= ./confs/scroller.conf

# master stuff
source= ./confs/master.conf

# dwindle stuff
source= ./confs/dwindle.conf

# overview stuff
source= ./confs/overview.conf

# overview stuff
source= ./confs/scratchpad.conf

# rules stuff
source= ./confs/rules.conf
