# Appearance
borderpx=0
gappih=0
gappiv=0
gappoh=0
gappov=0

rootcolor=0x000000ff
bordercolor=0x252530ff
dropcolor=0x8FBA7C55
splitcolor=0xEB441EFF
focuscolor=0x8ba9c1ff
urgentcolor=0xd8647eff
maximizescreencolor=0xaeaed1ff
scratchpadcolor=0xc9b1caff
globalcolor=0xbb9dbdff
overlaycolor=0x606079ff

cursor_size=24
cursor_theme=Kitty

