# keyboard
repeat_rate=35
repeat_delay=300
numlockon=0
xkb_rules_layout=us

# mouse (need relogin to make it apply)
mouse_natural_scrolling=0
mouse_accel_profile=2
mouse_accel_speed=0.5
axis_scroll_factor=2.0

# Trackpad (need relogin to make it apply)
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
trackpad_natural_scrolling=1
trackpad_accel_profile=2
trackpad_accel_speed=0.5
send_events_mode=0
drag_lock=0
swipe_min_threshold=1
button_map=0
trackpad_scroll_factor=2.0
