# layout support: tile,scroller,monocle,grid,deck,center_tile,vertical_tile,vertical_grid,vertical_deck,dwindle,fair,vertical_fair
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller


# Window Rule for apps
windowrule=tags:7,istagsilent:1,ignore_maximize:1,monitor:HDMI-A-1,shield_when_capture:1,appid:vesktop
windowrule=tags:7,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,shield_when_capture:1,appid:hnpfjngllnobngcgfapefoaidbinmjnm
windowrule=tags:7,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,shield_when_capture:1,appid:ibblmnobmgdmpoeblocemifbpglakpoi
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:cinhimbnkkaeohfgghhklpknlkffjgod
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:agimnkijcaahngcdmfeangaknmldooml
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:eikjhbkpemdappjfcmdeeeamdpkgabmk
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:pjibgclleladliembfgfagdaldikeohf
windowrule=tags:8,istagsilent:1,ignore_maximize:1,monitor:HDMI-A-1,appid:*tuner
windowrule=tags:9,istagsilent:1,isfullscreen:1,scroller_proportion:1.0,force_tearing:1,appid:osu*
windowrule=tags:9,istagsilent:1,isfullscreen:1,scroller_proportion:1.0,force_tearing:1,appid:Etterna
windowrule=tags:9,istagsilent:1,isfullscreen:0,appid:org.cachyos.hello
windowrule=tags:5,istagsilent:1,ignore_maximize:1,appid:anki
windowrule=tags:9,istagsilent:1,ignore_maximize:1,appid:Lutris
windowrule=tags:6,istagsilent:1,ignore_maximize:1,appid:winboat
windowrule=allow_csd:1,isopensilent:1,force_tiled_state:1,isoverlay:0,no_force_center:0,force_tiled_state:1,scroller_proportion:0.23,appid:Emulator,title:Android Emulator - pixel_.*
windowrule=allow_csd:1,isopensilent:1,istagsilent:1,focused_opacity:0.0,force_tiled_state:1,offsetx:45,offsety:0,width:60,height:512,isoverlay:0,no_force_center:1,scroller_proportion:0.23,appid:Emulator,title:^Emulator$
windowrule=isfloating:1,width:960,height:810,appid:filepicker
windowrule=width:1200,height:945,isfloating:1,appid:lazygit_popup
windowrule=width:960,height:810,isfloating:1,appid:foot_scrollback
windowrule=width:480,height:270,offsetx:100,offsety:100,isfloating:1,isglobal:1,isopensilent:1,force_tiled_state:0,title:Picture in picture
windowrule=width:640,height:360,isfloating:1,isglobal:1,appid:time
