# Scroller Layout Setting
scroller_structs=5
scroller_default_proportion=0.5
scroller_focus_center=0
scroller_prefer_center=0
scroller_prefer_overspread=1
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_proportion_preset=1,0.8,0.7,0.575,0.5,0.25
scroller_ignore_proportion_single=1
scroller_default_proportion_single=1.0
