# fcitx5 startups
exec-once= fcitx5 -d

# lxsession startup
exec-once=lxpolkit -a >/dev/null 2>&1 &

# udiskie startup
exec-once=udiskie -s >/dev/null 2>&1 &

# easyeffects startup
exec-once=easyeffects --gapplication-service >/dev/null 2>&1 &

# fnott startup
exec-once=fnott >/dev/null 2>&1 &

# statusbar startup
# exec-once=pkill yambar; yambar >/dev/null 2>&1 &

# wallpaper
# exec-once=swaybg -i ~/.config/mango/wallpaper.png -m fit >/dev/null 2>&1 &

# Screen tearing
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots

exec-once=/usr/lib/xdg-desktop-portal-wlr &

## Clipboard manager
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --watch cliphist store &

# idle lock
exec-once=~/.config/mango/scripts/idle.sh &

# battery notifier startup
exec-once=~/.config/mango/scripts/battery-notifier.sh >/dev/null 2>&1 &
