# Misc
xwayland_persistence=1
syncobj_enable=1
allow_lock_transparent=0
allow_shortcuts_inhibit=1
allow_tearing=1

focus_on_activate=0
sloppyfocus=0
warpcursor=1
cursor_hide_timeout=0
drag_tile_to_tile=1
drag_tile_small=1
drag_corner=4
drag_warp_cursor=1
axis_bind_apply_timeout=100

focus_cross_monitor=0
exchange_cross_monitor=0
focus_cross_tag=0
view_current_to_back=0
scratchpad_cross_monitor=0
single_scratchpad=0

enable_floating_snap=1
snap_distance=30
no_border_when_single=1
idleinhibit_ignore_visible=0
tag_carousel=0
drag_tile_refresh_interval=16.0
drag_floating_refresh_interval=16.0

